name: spenn
description: spenn loyality app.

version: 1.0.0+1

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: 0.5.2
  logger: ^0.6.0
  async: ^2.4.1
 
  # provider
  provider: ^4.1.3
  auto_route: ^0.3.1
  flutter_money_formatter: ^0.8.3
  carousel_slider: ^2.2.1
  flutter_icons: ^1.1.0
  get: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  auto_route_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
        - asset: assets/fonts/montserrat/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Semibold.otf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
          weight: 700  
  assets:
    - assets/images/icons/
    - assets/
    - assets/images/illustrations/
    - assets/images/products/